# parametros.py

# mapa
ANCHO_MAPA_SIMULAR = 15
LARGO_MAPA_SIMULAR = 15
PROB_RADIACION = 12
PROB_VIENTO = 5

# Entrenar
N_SIMULACIONES = 20
TIEMPO_SIMULACION = 24

ANCHO_MAPA_ENTRENAR = 15
LARGO_MAPA_ENTRENAR = 15